GET http://localhost:8080/getUserById/1
Accept: application/json

###

POST http://localhost:8080/createUser
Content-Type: application/json

{
  "name": "Jose",
  "email": "john@gmail.com",
  "password": "123456$",
  "age": 23
}